version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.8

jobs:
  lighthouse_report:
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          prCommentAccessToken: $LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN
          prCommentUrl: https://api.github.com/repos/Abhijeet-bluepineapple/nextjs-app-playground/pulls/${CIRCLE_PULL_REQUEST##*/}/reviews
          urls: https://nextjs-app-playground-kappa.vercel.app/

workflows:
  test:
    jobs:
      - lighthouse_report
