name: Assertions and Static Report

on: [push]

jobs:
  lighthouse-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer netlify-cli

      - name: Run Unlighthouse CI
        id: unlighthouse
        run: unlighthouse-ci --build-static --output=json > unlighthouse-output.json

      - name: Deploy to Netlify
        run: netlify deploy --dir=.unlighthouse --prod --message="New Release Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Upload Unlighthouse Output
        uses: actions/upload-artifact@v3
        with:
          name: unlighthouse-output
          path: unlighthouse-output.json

  comment:
    runs-on: ubuntu-latest
    needs: lighthouse-report
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Unlighthouse Output
        uses: actions/download-artifact@v3
        with:
          name: unlighthouse-output
          path: .

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const output = JSON.parse(fs.readFileSync('unlighthouse-output.json', 'utf8'));
            const scores = output.summary;
            const commentBody = `
              ## Unlighthouse Scores
              - **Performance**: ${scores.performance}
              - **Accessibility**: ${scores.accessibility}
              - **Best Practices**: ${scores.bestPractices}
              - **SEO**: ${scores.seo}
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
